import type { Locale } from "./config";
import type { RouteKey } from "./routes";

export type PageDefinition = {
  kind: "home" | "corporate" | "references" | "listing" | "detail";
  variant?: string;
  title: Record<Locale, string>;
  description: Record<Locale, string>;
  imageAlt: Record<Locale, string>;
  preload?: string;
};

const bilingual = (en: string, tr: string): Record<Locale, string> => ({ en, tr });
const page = (kind: PageDefinition["kind"], variant: string | undefined, enTitle: string, trTitle: string, enDescription: string, trDescription: string, preload?: string): PageDefinition => ({
  kind, variant, title: bilingual(enTitle, trTitle), description: bilingual(enDescription, trDescription),
  imageAlt: bilingual("Rota Robotik industrial robotic systems and engineering", "Rota Robotik endüstriyel robotik sistemleri ve mühendislik çözümleri"), preload,
});

export const pages: Record<RouteKey, PageDefinition> = {
  home: page("home", undefined, "Rota Robotik | Industrial Robotics and Automation Systems", "Rota Robotik | Endüstriyel Robotik ve Otomasyon Sistemleri", "Rota Robotik develops integrated robotic systems, automation lines and engineering solutions for welding, material handling, assembly and dispensing applications.", "Rota Robotik; kaynak, taşıma, montaj ve dozajlama uygulamaları için endüstriyel robotik sistemler, otomasyon hatları ve mühendislik çözümleri geliştirir.", "/media/home/hero-poster.webp"),
  about: page("corporate", "about", "About Us | Rota Robotik", "Hakkımızda | Rota Robotik", "Learn how Rota Robotik delivers end-to-end robotic systems engineering from concept and design through commissioning.", "Rota Robotik; tasarımdan devreye almaya uçtan uca robotik sistemler ve otomasyon çözümleri geliştirir.", "/media/expertise/commissioning/image-01.webp"),
  visionMission: page("corporate", "vision", "Vision & Mission | Rota Robotik", "Vizyon & Misyon | Rota Robotik", "Discover the vision and engineering mission guiding Rota Robotik in the future of manufacturing.", "Rota Robotik'in geleceğin üretimini tasarlayan vizyonunu ve mühendislik odaklı misyonunu keşfedin.", "/media/expertise/process-design/image-01.webp"),
  qualityPolicy: page("corporate", "quality", "Quality Policy | Rota Robotik", "Kalite Politikamız | Rota Robotik", "Explore Rota Robotik’s approach to quality, traceability, reliability and continuous improvement from design through commissioning.", "Rota Robotik'in tasarımdan devreye almaya uzanan kalite, güvenilirlik ve sürekli iyileştirme yaklaşımı.", "/media/expertise/measurement/image-01.webp"),
  certificates: page("corporate", "certificates", "Certificates | Rota Robotik", "Sertifikalar | Rota Robotik", "View Rota Robotik’s ISO 9001:2015 and ISO 14001:2015 certificates and document management approach.", "Rota Robotik'in kalite, teknik uygunluk ve proje dokümantasyonu yaklaşımı hakkında bilgi alın.", "/media/expertise/electric-design/image-01.webp"),
  references: page("references", undefined, "References | Robotic Automation Projects | Rota Robotik", "Referanslar | Robotik Otomasyon Projeleri | Rota Robotik", "Explore Rota Robotik references across automotive, home appliances, robotic welding, assembly, material handling and conveyor systems.", "Rota Robotik’in otomotiv, beyaz eşya, robotik kaynak, montaj hattı, taşıma ve konveyör sistemi referanslarını inceleyin.", "/media/corporate/about-cover.webp"),
  expertise: page("listing", "expertise", "Robotics Engineering Expertise | Rota Robotik", "Robotik Mühendislik Uzmanlıkları | Rota Robotik", "Explore our capabilities in process simulation, mechanical design, manufacturing, electrical engineering, automation, robot programming and commissioning.", "Proses tasarım ve simülasyon, mekanik tasarım, elektrik projelendirme, imalat, otomasyon ve robot yazılımı ile devreye alma uzmanlıklarımızı keşfedin.", "/media/corporate/about-cover.webp"),
  processDesignSimulation: page("detail", "process-design", "Process Design and Simulation | Rota Robotik", "Proses Tasarım ve Simülasyon | Rota Robotik", "Layout design, process equipment selection, cycle time analysis and robot reach validation for reliable automation investments.", "Rota Robotik ile layout tasarımı, proses ekipmanı seçimi ve robot erişim doğrulama çalışmaları.", "/media/expertise/process-design/image-01.webp"),
  mechanicalDesign: page("detail", "mechanical-design", "Mechanical Design | Rota Robotik", "Mekanik Tasarım | Rota Robotik", "Mechanical engineering for fixtures, grippers, conveyors, robotic positioners and customized machines.", "Fikstür, gripper, konveyör ve özel makine tasarımı için Rota Robotik mühendislik hizmetleri.", "/media/expertise/mechanical-design/image-01.webp"),
  measurementQuality: page("detail", "measurement", "3D Measurement and Quality Control | Rota Robotik", "3D Ölçüm ve Kalite Kontrol | Rota Robotik", "High-precision 3D measurement, dimensional inspection, reporting and quality control for robotic systems and production equipment.", "Robotik sistemler ve üretim ekipmanları için hassas 3D ölçüm, boyutsal kontrol ve kalite doğrulama hizmetleri.", "/media/expertise/measurement/image-01.webp"),
  precisionMachining: page("detail", "machining", "Precision Machining | Rota Robotik", "Talaşlı İmalat | Rota Robotik", "Precision machining solutions for complex components, tight tolerances and repeatable quality in robotic systems.", "Robotik sistemler için hassas parça ve bileşen üretim yaklaşımımız.", "/media/expertise/machining/image-01.webp"),
  mechanicalElectricalManufacturing: page("detail", "mechanic-electric", "Mechanical and Electrical Manufacturing | Rota Robotik", "Mekanik – Elektrik İmalat | Rota Robotik", "Controlled mechanical and electrical manufacturing, assembly, panel production and on-site installation services.", "Mekanik ve elektrik imalat, montaj ve saha kurulum hizmetleri.", "/media/expertise/mechanic-electric/image-01.webp"),
  electricalEngineering: page("detail", "electric-design", "Electrical Engineering | Rota Robotik", "Elektrik Projelendirme | Rota Robotik", "Electrical and pneumatic design, equipment selection, safety architecture and control infrastructure engineering.", "Elektrik ve pnömatik tasarım, saha ekipmanı seçimi ve kontrol altyapısı projelendirme hizmetleri.", "/media/expertise/electric-design/image-01.webp"),
  automationSoftware: page("detail", "automation-software", "Automation Software | Rota Robotik", "Otomasyon Yazılımı | Rota Robotik", "PLC programming, HMI, SCADA, drive integration and reliable communication across robotic automation systems.", "PLC, HMI, SCADA ve robot haberleşmesi için otomasyon yazılımı çözümleri.", "/media/expertise/automation-software/image-01.webp"),
  robotProgramming: page("detail", "robot-software", "Robot Programming and Offline Programming | Rota Robotik", "Robot Yazılımı ve Offline Programlama | Rota Robotik", "Robot path planning, signal architecture, simulation and offline programming for faster, safer commissioning.", "Robot yolu, sinyal yapısı, simülasyon ve offline programlama hizmetleri.", "/media/expertise/robot-software/image-01.webp"),
  commissioning: page("detail", "commissioning", "System Installation and Commissioning | Rota Robotik", "Sistem Kurulum ve Devreye Alma | Rota Robotik", "On-site installation, electrical testing, PLC-HMI and robot commissioning, process trials and production acceptance.", "Robotik sistem kurulum, saha testi, proses denemesi ve üretim kabul hizmetleri.", "/media/expertise/commissioning/image-01.webp"),
  technologies: page("listing", "technologies", "Robotic Production Technologies | Rota Robotik", "Robotik Üretim Teknolojileri | Rota Robotik", "Explore spot and arc welding, robotic material handling, palletizing, conveyor, assembly, dispensing and collaborative robot technologies.", "Punta ve gazaltı kaynak, robotik taşıma, paletleme, konveyör, montaj, dozajlama ve işbirlikçi robot teknolojilerini keşfedin.", "/media/corporate/about-cover.webp"),
  weldingTechnologies: page("detail", "welding", "Welding Technologies | Rota Robotik", "Kaynak Teknolojileri | Rota Robotik", "Integrated robotic welding cells for spot and arc welding with repeatable quality, process control and production performance.", "Punta ve gazaltı kaynak için robotik kaynak hücreleri ve entegre üretim çözümleri.", "/media/technologies/welding/image-01.webp"),
  materialHandling: page("detail", "material-handling", "Material Handling Systems | Rota Robotik", "Taşıma Sistemleri | Rota Robotik", "Robotic material handling, pick and place, conveyor and palletizing systems integrated into production flow.", "Robotik malzeme taşıma, pick and place, konveyör ve paletleme sistemleri.", "/media/technologies/material-handling/cover.webp"),
  assemblySystems: page("detail", "assembly", "Assembly Systems | Rota Robotik", "Montaj Sistemleri | Rota Robotik", "Integrated robotic assembly systems for consistent product quality, traceability and reliable production.", "Kaliteli ve tutarlı üretim için entegre robotik montaj sistemleri.", "/media/technologies/assembly/image-01.webp"),
  sealingDispensing: page("detail", "dispensing", "Sealing and Dispensing Systems | Rota Robotik", "Mastikleme / Dozajlama Sistemleri | Rota Robotik", "Controlled robotic sealing, adhesive application and two-component dispensing systems with process traceability.", "Robotik mastikleme, yapıştırma ve iki komponentli dozajlama sistemleri.", "/media/technologies/dispensing/cover.webp"),
  collaborativeRobots: page("detail", "collaborative-robots", "Collaborative Robot Systems | Rota Robotik", "İşbirlikçi Robotlu Sistemler | Rota Robotik", "Flexible collaborative robot systems engineered around safety, ergonomics, cycle time and operator interaction.", "Esnek üretim süreçleri için işbirlikçi robotlu sistem çözümleri.", "/media/technologies/collaborative-robots/image-01.webp"),
  contact: page("listing", "contact", "Contact | Rota Robotik Sistemler", "İletişim | Rota Robotik Sistemler", "Contact the Rota Robotik engineering team to discuss your robotic automation project by WhatsApp, email or our project form.", "Robotik otomasyon projeniz için Rota Robotik mühendislik ekibine ulaşın. Telefon, e-posta, adres, iletişim formu ve İSTİM Tuzla ofisi haritası."),
};
